spring.application.name=event

spring.datasource.url=jdbc:postgresql://localhost:5432/event
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=7c3d9a8e2b1f4567890abcdef12345678
jwt.expiration=86400000